### ISSUE TITLE
mdn-compat-data-explorer.herokuapp.com application error

### ISSUE THREAD

**Issue by grahamperrin** [connorshea/mdn-compat-data-explorer#200]
https://github.com/connorshea/mdn-compat-data-explorer#user-content-deployment refers to https://mdn-compat-data-explorer.herokuapp.com/

> ###  Application error
> 
> An error occurred in the application and your page could not be served. …

**Comment by connorshea** [comment]
Yup, unfortunately I’m running on the Heroku free tier and usually run out of dyno hours around the 14th of the month, it’ll be back on December 1st. I’ve been looking into improving this.

Sorry for the inconvenience!

**Comment by connorshea** [comment]
Alright, I've fixed this issue so now the site should be up 24/7. I've also updated it to a much newer version of the mdn-compat-data package so the information should be more accurate and cover more surface area.
